### ISSUE TITLE
Invalid HTML produced

### ISSUE THREAD

**Issue by Moonbase59** [BoboTiG/ebook-reader-dict#1202] opened 2022-02-02 18:03 UTC
Using

```bash
python3 -m wikidict fr --gen-dict='cercle unité' --output=test_wik
```

and then inspecting the generated `ce.raw.html` shows that we produce some invalid HTML. Here is a beautified version of the output:

```html
<w>
  <p><a name="cercle unité" /><b>cercle unité</b> \sɛʁ.kl‿y.ni.te\ <i>m.</i><br /><br />
  <p>Des mots <i>cercle</i>, figure géométrique, et <i>unité</i>.</p><br />
  <ol>
    <li><i>(Mathématiques)</i></li>
    <ol style="list-style-type:lower-alpha">
      <li>On appelle cercle unité de <img style="height:100%;max-height:0.8em;width:auto;vertical-align:bottom"
          src="data:image/gif;base64,R0lGODdhEgARAIEAAAAAAP///wAAAAAAACwAAAAAEgARAEAITwADCBQIoKBBgwEKJgRAkOHAhxAfHpwIUWHCiAMtKrSIMSJFiQgXiuwosSFJjwdROsyYcmFLkRxBOty4EiVBkydvjsxJMyfLnRVrupzYMiAAOw==" />, l’ensemble des nombres complexes de module égal
        à 1 : <img style="height:100%;max-height:0.8em;width:auto;vertical-align:bottom"
          src="data:image/gif;base64,R0lGODdhzQAZAIEAAAAAAP///wAAAAAAACwAAAAAzQAZAEAI/wADCBxIsKDBgwgTKlzIsKHDhwwBQJQIsWJDABgpEsQYgKNBjxYrghyYsaRGhBlDchwZUiBIkylJnmz5MObHmStP2qTpkGVHmDsL+pxY8ibFogdfAvU4lKfCoC6bOp1KtapIq1iz/tx6U2vSmV4vIpUpVSjYhGWzQv2pU+LQtFPXyhS7VK7LqFR9vj0b1q7dsBHhAqa5VjDewT011iX7t6phxGxhcg1ck6/asRtxuj37mGfnwECfHkVr2WxlyGS/tp2cWXRdyaSFZi7Nmuhhp0xnm0b5GvZCuSNzfnXd++/e0y2Fx13Nm3TxxlH57vWNOvjr35iJhjYrffPi25ALf8hGHZ02eeRdE5/nPf68yfWAH7dPbj2o8tnml+cPj5S6aPTxvWdUa8fxB99w06mnYHUJzlUgYnothR10BFpmmFLb1TYYcKs9qNpzpbGE4YTJgUfYUYqJaCGIgnFY4XAQhgjXfB2ZSN+AuzHYHVObwRhjc2KdqKFKmgGpo5FbRTghiP9xl+OTFt2Xo1QjtjZkec/RhSSWAjLIXYZbitQbY0BeZ2OAnNG4oU64SXhZmjVSdiCOc7pWp2fdAXinmvzx6Z6FE91ZHkEBAQA7" />.
        <br> Il apparait alors clairement que <img style="height:100%;max-height:0.8em;width:auto;vertical-align:bottom"
          src="data:image/gif;base64,R0lGODdh1wAcAIEAAAAAAP///wAAAAAAACwAAAAA1wAcAEAI/wADCBxIsKDBgwgTKlx4EACAgg4dMpxIsaLFixgzJpQo0WBHjRU/hnwo8KPIhScjggwJkWSAiC4vqpQZs6RIjjVtrhzZcubOjSdf5my5M2bQoAp9ejRaEynSnz+VQiU6tSpMnlV75nyaFSTMoUtdmgTbNSpXjVcx+vxK1ClZoV/jpkV49OZZtSml9lzJNCxesXLj6lwaVm5ZoIXnWlRMMDDWjE0FD2RsMzBJqWyF+j3MeTHgzqBDl8VZWLRelJ8HU3RsumHmiZbxbtbpVrRm16+vSoad9+1kygz7Nj4d/O7vh7V/36YKuu5l4Hzroi56fPZq4cvz4n6+XHlSy4YR7/8dLpuu3eLUq5NX7fo7c/bebXsOTdxs+KR/m281Ln/7aN/9FQVgV9AFSGBf9Rmo4IIMHhhfg7zxZ9tcisVWWYJTSQgXYK+NhKFV5ml44YftvadZcvQNyNxY813YWlskdlegeMMhOJSIXqm4XnY69ubhbhu9F6N111lHGmGm3XjfWkPCNd53Onq0o3o0HQced0jSpiSUVyboXI1ZdekeX1SWWWRlqmmX5Ylb6rdfh2FKx6WF+KH5ZISNPajmZkeaqFWXb/mYYmS+4SilmRp6iR188PXp5IRvckjTU2mRaGieVsYHHXgPPsroaazJ59aMqJEFZHFNlpQYkRuy5lxqYEIeGKKbsh7qWZTlTVmrVpxdmmKV+tWI664ZEhsVsQEBADs=" />.
      </li>
      <li>De même, on appelle cercle unité de <img style="height:100%;max-height:0.8em;width:auto;vertical-align:bottom"
          src="data:image/gif;base64,R0lGODdhGgAWAIEAAAAAAP///wAAAAAAACwAAAAAGgAWAEAIdQADCBxIsGBBAAgRDlSocCGAAA0dHnzYMGFEgxgzahQYkeFDiBY/bgRJUmLCkSgPSuRI8WNIkQQveozZ0mFIliBnpsTZsebOny9/avT48uZQkTo55pzIVKZPnE1htnRZlGdRmBtnJkWpc2vWpycvGryK1KjBgAA7" />,
        l’ensemble <img style="height:100%;max-height:0.8em;width:auto;vertical-align:bottom"
          src="data:image/gif;base64,R0lGODdheQIeAIEAAAAAAP///wAAAAAAACwAAAAAeQIeAEAI/wADCBxIsKDBgwgTKlzIsKHDhxAjSpy4EIDFixgzatzIsaPHjyApihxJsqTJkyhTqlzJsqXEiwYxuhRo8WDNmQ1vzqypMwAAnz1p/kQZFGJRhUeJDsU5EGbMpCqPQsWpU2bJqTmXWiWItaJWpy6XNv25lWHPsg6LOgXL9KnYsW8Lsk0bNGlXkHG5kt0LlORcvWa7JsSLFq7cvG3dDhZM8S/Qt1DV8syI8C9jjYfFsrUs2SZir3Gx4q1oOHPEzWMBq1acGLTnxpelfm59WjJf2k/9MsZ9OLHj3bwd8648+/HwwS+BT+x8HPbw4s2/RoWuVzhuys0fU/e9Pbv3mN9FFv+ODrasde6vq6+9i71078DdAZ81LrS9eMjY5yrvC19/3fgnCbffcnnJhhZm6nGGX3cbaTfUR54tmF5tErq23Gru1QYXhPy952BuVBUo4oOTaUfcTeN1iBSAqVVVYn+mYRhhfSoSaNR6A7L0W44agpihTzTKh1+EJGrGmYebnWVgkcSdiJhV56XWmHpSmugkgjUmyVp4LVHHIpekLcbjd1+CaaaZZaJ55pRrtukml/YFmOabdNZp55140skRej4+N2dWHDaplFFVRlfoTuON2aOHwaVI4J8f9nlflAE6mVycdPVJKaITZgdcRyuq+OKhut236EqKXjojU7L5GaN3/4n/6Fx1D4GKFKObnpgca7kSOZqgtF5J4asydqqhrWHNFmeDmdYa64bWEbapgMpKW+2WQdLnX5ahBboYkkoa6SuzxQKKrLGn/Ujfousd2qqVlxL2LbGZKbctupLeyN+osMkKWqqkrjjko/LCB+y43uZ7L7Y0fmUbvcjV53Cw2f6446MQM/oSxULdeK27/ibYa6kKh8txvSQeLHBs5GIp5paimXwVgPlBKueIbb2L8oLlkevWjt0iiNmvO4eq65XxYRpmggxLvGeN8D6MpoK7Egmvunba5aibMm0dntcpFTZyawDryN6Z9trsFZV5tu220W/HLffcdNdt9905Kz1S2Xj3/+3334D/vSzfHuupdsX/Et7v2LoZyfikzwae7OG0Pf4vxk7/vJflhed7HeVNoqg335YrTnKIiZq+qsbcubz3mE+z7rHeYY87O+3zUkwt6J6rPiynSnI7nanOckq2gXnjy2qFsDKPdVYZ174a2C+fGiTncqJrnmAH6py4vsEHHzbPHO+3W/cDV6518p6jHr36zgds8MnCEgpyjrnC9C7n1n4mNa9Ji5zs3rc20W0ldsQD4ADX5izncc9agFLZzhLGOqp1LFsuUpd/HuieJGWQYWL70garlSZxEbB6DrLV/nzXrPdRj17rY6CNumazqdhwhC+EmsDA5TpEPQl7gVndBf+l1JkDBq199aqSB8t1JCTucIFDvBDi1lU8JUqHiT5rVNM2pKpy6RCKBSwS/kZXnBxCr4FgPN4P2Vc+rR0xhUKMYuIc18Y3YhFzXpRfWoqVNv+ZMGAuGlD/cufFyXQLhXLUoyLD2CIG2XGRhhwUGvM4RwrGUZGDJCTINNmX/wjRk5IKZB0/uUYJZuhs4jnZBzkpI1DiypLD653DDOjHLC7ylq8JH3sEmEgepqqPPTwO0NjIx1X2rGJLQt8jRXnKZEbrh27EXRorM0G2aU5osRLdFsmjvAh604nXBGLnOsg7fb2unNNBp+xYaBJxGu9oqEKgTbqYrG0K03vm7FQM84Q/PHZ26Y+Ga103yaTOdpaxoASr4j+Zg7YmKtR2A+VaLRG6UHeijqJJnObn3oRKuvnTapILaSxFStKSmvSkIwkIADs=" />.
      </li>
    </ol>
  </ol>
  </p>
</w>

</html>
```

With strict parsing engines, like MuPDF (used in KOReader, expects strict XML), this might pose problems, and it should be easy to repair.

What I immediately found:

1. `<p>` within `<p>`. It is illegal to have another block element within a `<p>`. Either close the heading part with `</p>` (and remove the one at the end), or use a proper heading element.
2. A mixture of `<br />` and `<br>` elements. For XHTML and XML rendering engines, we should probably use `<br/>` only, which also shouldn’t harm HTML renderers.
3. Images have `vertical-align:bottom`. Why? Looks bad, see images in https://github.com/BoboTiG/ebook-reader-dict/issues/1198#issuecomment-1028063067. Maybe better to drop it, or use `baseline`.

**Comment by lasconic** [comment] 2022-02-04 20:02
1. `<ol>` is also a block element... it needs some testing to get rid of the `<p>`
2. `<br>` comes from the wiki code directly. It seems this line https://github.com/BoboTiG/ebook-reader-dict/blob/26fe4214be67d1743c436fde7919dd7426b511f0/wikidict/utils.py#L339  is supposed to remove it completely but the regex is wrong. @BoboTiG what's the expected behavior ? if we want to remove all sort of <br>, <br />, we can use `<br\s*/?>`
3. it needs some more testing

**Comment by lasconic** [comment] 2022-02-04 20:11
1. I just tried to replace the first `<p></p>` by `<div></div>` and the dictionary is broken on Kobo... So it's not optional... This "global" `<p></p>` is used only for Kobo so it's not worth changing it.
2.
3. See screenshot, `vertical-align:baseline` doesn't make a huge difference does it?
![screen_008](https://user-images.githubusercontent.com/234271/152596609-7ead46ce-412e-43e0-95ea-47ecc1b798fd.png)

**Comment by BoboTiG** [comment] 2022-02-04 22:13
> is supposed to remove it completely but the regex is wrong. @BoboTiG what's the expected behavior ? if we want to remove all sort of `<br>, <br />`, we can use `<br\s*/?>`

God catch, the regex should remove all kinds of `<br>`.


> I just tried to replace the first `<p></p>` by `<div></div>` and the dictionary is broken on Kobo... So it's not optional... This "global" `<p></p>` is used only for Kobo so it's not worth changing it.

:+1: 

> See screenshot, `vertical-align:baseline` doesn't make a huge difference does it?

It does not seem worth to change that, it would only produce bigger dictionaries.

**Comment by BoboTiG** [comment] 2022-05-14 03:10
Closing the issue since we fixed a part of the request. The rest is too device-specific, and therefore should not be changed.

**Closed by BoboTiG** 2022-05-14 03:10 UTC
Labels: bug
