### ISSUE TITLE
Word types not listed or separated into different groups

### ISSUE THREAD

**Issue by Chairzard** [BoboTiG/ebook-reader-dict#2188] opened 2024-10-11 17:46 UTC
I'm not sure if this is a bug fix or feature request, I apologize!

I just tried out this dictionary but found it difficult to use as different parts of speech (nouns, adjectives, etc) are all lumped together in one numbered list, rather than being separated into different lists based on word type like they are on the Wiktionary website (see first/second screenshot; in the first there's a 6 item list with no distinctions, but in the second there's a 2 & 4 item list, separated by word type). There are also no indicators for the word types anywhere (there's no way to tell if a definition is for a noun/adjective/etc). I am not sure if this is intentional behavior or a bug.

Tested with the English No Entomology Kobo file (on my Kobo Clara 2E) and the Stardict file (on KOReader for Linux).

Thank you all for your work on this project!

**1 (Screenshot from KOReader using the Stardict file):**

> ![1](https://github.com/user-attachments/assets/fec61e4e-e52c-42c7-b21d-e4ec6efb8646)

**2 (Screenshot from the Wiktionary page for the same word):**

> ![2](https://github.com/user-attachments/assets/b4ab8174-63cb-4ad4-b513-8034cfe10e14)

The Stardict file lists version 3.0.0, dated 2024-10-01.

**Comment by BoboTiG** [comment] 2024-10-11 18:56
Duplicate of #1149.

**Closed by BoboTiG** 2024-10-11 18:56 UTC
