### ISSUE TITLE
PyGlossary conversion errors (missing images)

### ISSUE THREAD

**Issue by Moonbase59** [BoboTiG/ebook-reader-dict#1183] opened 2022-01-31 23:12 UTC
Note from @BoboTiG: issue tightly coupled to #1182, interesting details can be found there too.

---

I just downloaded, parsed and rendered the EN Wiktionary, and it apparently has some problems with erroneous and/or missing GIFs:

[output.txt](https://github.com/BoboTiG/ebook-reader-dict/files/7974828/output.txt)

All of the `.gif` files in `data/en/res` appear to be very ugly rendered fomulae (?).

**Comment by BoboTiG** [comment] 2022-02-01 04:00
@ilius I saw those errors since the beginning. As files are created by PyGlossary, is it expected to have such errors?

**Comment by ilius** [comment] 2022-02-01 04:22
What version of PyGlossary are you using?
Try again the latest tag or main branch.

**Comment by BoboTiG** [comment] 2022-02-01 04:26
We are running the latest version. FTR those errors were always present, here is an example 2 months ago: https://github.com/BoboTiG/ebook-reader-dict/runs/4343135917?check_suite_focus=true

**Comment by BoboTiG** [comment] 2022-02-01 04:27
I just did not take them into account, too lazy :)
But there may be important or minor, and then maybe the exception could be silent.

**Comment by ilius** [comment] 2022-02-01 05:41
Please make sure `~/.cache/pyglossary/` exists, or try again with latest tag.

**Comment by BoboTiG** [comment] 2022-02-01 06:17
I see https://github.com/ilius/pyglossary/commit/ea1ddf6d58529f212b3a6bcf96394fe09490d145 👍 :)

If the next version does not fix errors, I'll have a look and report any potential improvement/bug to the PyGlossary repo.

**Comment by ilius** [comment] 2022-02-01 06:58
> I see ilius/pyglossary@ea1ddf6 👍 :)

That's not a bug fix.
4.4.1 should work too.

**Comment by Moonbase59** [comment] 2022-02-01 11:33
@ilius: True that pyglossary generates the GIFs? If yes, ever thought of generating 8-bit grayscale+alpha PNGs instead? They aren’t much bigger but might provide cleaner output.

And would you know if that’s supported by readers?

**Comment by ilius** [comment] 2022-02-01 18:57
U-huh, got it!
https://github.com/ilius/pyglossary/commit/ecf386b80aa24d34a8dc4f31c13b2eeb79260cd3
That was one of weirdest bug I ever encountered.

**Comment by ilius** [comment] 2022-02-01 19:00
I can add an option to convert gif to png if you want.

**Comment by Moonbase59** [comment] 2022-02-01 19:46
GIF→PNG wouldn’t help much, I think. One of the problems is that the GIF already has a white background, which looks odd in readers using a background color (like GoldenDict).
Who/what creates the images in the first place?

**Comment by BoboTiG** [comment] 2022-02-01 19:53
Actually, on Kobo there is no background color. Here is an example: [cercle unité](https://www.tiger-222.fr/img/c7/dict-cercle_unite.png). I checked with the dark mode enabled, and still no background displayed.

I think we are talking about 2 kinds of GIFs, ones generated by the current project (<math>, <chem>, and some hieroglyphs), and one created by PyGlossary. The former is using embedded GIFs as `<img src="data:image/gif;base64,..."/>' `. The later is taking that information and turns it into real GIFs.

Maybe should we look at how PyGlossary is creating those files, maybe is there something to tweak?

**Comment by Moonbase59** [comment] 2022-02-01 20:03
Ah, interesting. Screenshot from an actual reader? It looks way better than on my GoldenDict (which does use a yellowish background, and thus we get "white blocks"). Too bad my Tolinos support none of the formats we currently generate. Must give KOReader a spin, I guess.

Where do the project-generated GIFs come from? I really wonder if SVG could be done (for scaling on any device/device resolution).

**Comment by BoboTiG** [comment] 2022-02-01 20:08
Here is the same work using dark theme:

![screen_001](https://user-images.githubusercontent.com/2033598/152043233-932cb8d0-b90c-49f7-8f56-f61104d8331e.png)

And yes, it is the real screenshot on the Kobo Libra H2O.

**Comment by Moonbase59** [comment] 2022-02-01 20:17
Looks like PIL only handles raster-type images. We might be able to use 'LA', though (8-bit grayscale+alpha).

**Comment by Moonbase59** [comment] 2022-02-01 20:20
I haven’t yet installed FR, can I use a fast command to get only "cercle unité" in a dict, for comparison?

**Comment by BoboTiG** [comment] 2022-02-01 20:22
> I haven’t yet installed FR, can I use a fast command to get only "cercle unité" in a dict, for comparison?

Of course:

```shell
mkdir  test_wik
python -m wikidict fr --gen-dict='cercle unité' --output=test_wik
```

You can adapt the command to use a German work (or English one like `graph`).

**Comment by Moonbase59** [comment] 2022-02-01 20:25
Just love this project for providing a well thought-out foundation! What steps go before?
Download/parse/render?

**Comment by BoboTiG** [comment] 2022-02-01 20:27
This is a sigle step, we introduced it to help debugging such issues ;)

**Comment by lasconic** [comment] 2022-02-01 20:28
And since a couple hours.

```
python -m wikidict fr --gen-dict='cercle unité' --output=test_wik --format=stardict
```
To get a stardict file, instead of kobo.

**Comment by Moonbase59** [comment] 2022-02-01 20:29
But it will use an already downloaded dump, right? 'cause I’m just downloading FR :-)

**Comment by Moonbase59** [comment] 2022-02-01 20:30
Wow! Ok, let me abort and try. D/Ling FR can be done later then.

**Comment by Moonbase59** [comment] 2022-02-01 20:31
Oops:

```bash
matthias@e6510:~/Projekte/ebook-reader-dict$ python3 -m wikidict fr --gen-dict='cercle unité' --output=test_wik --format=stardict
>>> Generated dict-fr-fr.df (4,595 bytes)

Traceback (most recent call last):
  File "/home/matthias/.local/lib/python3.8/site-packages/pyglossary/glossary.py", line 905, in _read
    reader.open(filename)
  File "/home/matthias/.local/lib/python3.8/site-packages/pyglossary/plugins/ebook_kobo_dictfile.py", line 71, in open
    TextGlossaryReader.open(self, filename)
  File "/home/matthias/.local/lib/python3.8/site-packages/pyglossary/text_reader.py", line 84, in open
    self._open(filename)
  File "/home/matthias/.local/lib/python3.8/site-packages/pyglossary/text_reader.py", line 80, in _open
    self.loadInfo()
  File "/home/matthias/.local/lib/python3.8/site-packages/pyglossary/text_reader.py", line 131, in loadInfo
    self._pendingEntries.append(self.newEntry(word, defi))
  File "/home/matthias/.local/lib/python3.8/site-packages/pyglossary/text_reader.py", line 113, in newEntry
    return self._glos.newEntry(
  File "/home/matthias/.local/lib/python3.8/site-packages/pyglossary/glossary.py", line 742, in newEntry
    return Entry(
  File "/home/matthias/.local/lib/python3.8/site-packages/pyglossary/entry.py", line 285, in __init__
    raise TypeError(f"invalid defi type {type(defi)}")
TypeError: invalid defi type <class 'tuple'>
Reading file 'test_wik/dict-fr-fr.df' failed.
>>> Generated dict-fr-fr.zip (22 bytes)
matthias@e6510:~/Projekte/ebook-reader-dict$ 
```

**Comment by BoboTiG** [comment] 2022-02-01 20:31
I hit the issue too, I am currently looking into it :watch:

**Comment by Moonbase59** [comment] 2022-02-01 20:33
The .df looks ok, but the zip is empty.

**Comment by ilius** [comment] 2022-02-01 20:57
https://github.com/ilius/pyglossary/commit/e864fa4cd29bcba024dc10e6b93eda259c228449
Please try again with latest master.

**Comment by Moonbase59** [comment] 2022-02-01 21:11
Okayyy… Next dumb question: How would I install the latest master over my PIP3-installed pyglossary?

**Comment by ilius** [comment] 2022-02-01 21:53
`sudo python3 setup.py install`
or
`python3 setup.py install --user`

**Comment by BoboTiG** [comment] 2022-02-01 21:53
FTR I added a test case to reproduce the current error:

```
# from up-to-date master branch
$ python -m pytest tests/test_5_gen_dict.py cercle
```

**Comment by BoboTiG** [comment] 2022-02-01 21:58
It seems that DictFile is causing issues with PyGlossary:

```
@ cercle unité
: \sɛʁ.kl‿y.ni.te\  <i>m.</i>
<html><p>Des mots <i>cercle</i>, figure géométrique, et <i>unité</i>.</p><br />
<ol><li><i>(Mathématiques)</i></li><ol style="list-style-type:lower-alpha"><li>On appelle cercle unité de <img style="height:100%;max-height:0.8em;width:auto;vertical-align:bottom" src="data:image/gif;base64,R0lGODdhEgARAIEAAAAAAP///wAAAAAAACwAAAAAEgARAEAITwADCBQIoKBBgwEKJgRAkOHAhxAfHpwIUWHCiAMtKrSIMSJFiQgXiuwosSFJjwdROsyYcmFLkRxBOty4EiVBkydvjsxJMyfLnRVrupzYMiAAOw=="/>, l’ensemble des nombres complexes de module égal à 1 : <img style="height:100%;max-height:0.8em;width:auto;vertical-align:bottom" src="data:image/gif;base64,R0lGODdhzQAZAIEAAAAAAP///wAAAAAAACwAAAAAzQAZAEAI/wADCBxIsKDBgwgTKlzIsKHDhwwBQJQIsWJDABgpEsQYgKNBjxYrghyYsaRGhBlDchwZUiBIkylJnmz5MObHmStP2qTpkGVHmDsL+pxY8ibFogdfAvU4lKfCoC6bOp1KtapIq1iz/tx6U2vSmV4vIpUpVSjYhGWzQv2pU+LQtFPXyhS7VK7LqFR9vj0b1q7dsBHhAqa5VjDewT011iX7t6phxGxhcg1ck6/asRtxuj37mGfnwECfHkVr2WxlyGS/tp2cWXRdyaSFZi7Nmuhhp0xnm0b5GvZCuSNzfnXd++/e0y2Fx13Nm3TxxlH57vWNOvjr35iJhjYrffPi25ALf8hGHZ02eeRdE5/nPf68yfWAH7dPbj2o8tnml+cPj5S6aPTxvWdUa8fxB99w06mnYHUJzlUgYnothR10BFpmmFLb1TYYcKs9qNpzpbGE4YTJgUfYUYqJaCGIgnFY4XAQhgjXfB2ZSN+AuzHYHVObwRhjc2KdqKFKmgGpo5FbRTghiP9xl+OTFt2Xo1QjtjZkec/RhSSWAjLIXYZbitQbY0BeZ2OAnNG4oU64SXhZmjVSdiCOc7pWp2fdAXinmvzx6Z6FE91ZHkEBAQA7"/>. <br> Il apparait alors clairement que <img style="height:100%;max-height:0.8em;width:auto;vertical-align:bottom" src="data:image/gif;base64,R0lGODdh1wAcAIEAAAAAAP///wAAAAAAACwAAAAA1wAcAEAI/wADCBxIsKDBgwgTKlx4EACAgg4dMpxIsaLFixgzJpQo0WBHjRU/hnwo8KPIhScjggwJkWSAiC4vqpQZs6RIjjVtrhzZcubOjSdf5my5M2bQoAp9ejRaEynSnz+VQiU6tSpMnlV75nyaFSTMoUtdmgTbNSpXjVcx+vxK1ClZoV/jpkV49OZZtSml9lzJNCxesXLj6lwaVm5ZoIXnWlRMMDDWjE0FD2RsMzBJqWyF+j3MeTHgzqBDl8VZWLRelJ8HU3RsumHmiZbxbtbpVrRm16+vSoad9+1kygz7Nj4d/O7vh7V/36YKuu5l4Hzroi56fPZq4cvz4n6+XHlSy4YR7/8dLpuu3eLUq5NX7fo7c/bebXsOTdxs+KR/m281Ln/7aN/9FQVgV9AFSGBf9Rmo4IIMHhhfg7zxZ9tcisVWWYJTSQgXYK+NhKFV5ml44YftvadZcvQNyNxY813YWlskdlegeMMhOJSIXqm4XnY69ubhbhu9F6N111lHGmGm3XjfWkPCNd53Onq0o3o0HQced0jSpiSUVyboXI1ZdekeX1SWWWRlqmmX5Ylb6rdfh2FKx6WF+KH5ZISNPajmZkeaqFWXb/mYYmS+4SilmRp6iR188PXp5IRvckjTU2mRaGieVsYHHXgPPsroaazJ59aMqJEFZHFNlpQYkRuy5lxqYEIeGKKbsh7qWZTlTVmrVpxdmmKV+tWI664ZEhsVsQEBADs="/>.</li><li>De même, on appelle cercle unité de <img style="height:100%;max-height:0.8em;width:auto;vertical-align:bottom" src="data:image/gif;base64,R0lGODdhGgAWAIEAAAAAAP///wAAAAAAACwAAAAAGgAWAEAIdQADCBxIsGBBAAgRDlSocCGAAA0dHnzYMGFEgxgzahQYkeFDiBY/bgRJUmLCkSgPSuRI8WNIkQQveozZ0mFIliBnpsTZsebOny9/avT48uZQkTo55pzIVKZPnE1htnRZlGdRmBtnJkWpc2vWpycvGryK1KjBgAA7"/>, l’ensemble <img style="height:100%;max-height:0.8em;width:auto;vertical-align:bottom" src="data:image/gif;base64,R0lGODdheQIeAIEAAAAAAP///wAAAAAAACwAAAAAeQIeAEAI/wADCBxIsKDBgwgTKlzIsKHDhxAjSpy4EIDFixgzatzIsaPHjyApihxJsqTJkyhTqlzJsqXEiwYxuhRo8WDNmQ1vzqypMwAAnz1p/kQZFGJRhUeJDsU5EGbMpCqPQsWpU2bJqTmXWiWItaJWpy6XNv25lWHPsg6LOgXL9KnYsW8Lsk0bNGlXkHG5kt0LlORcvWa7JsSLFq7cvG3dDhZM8S/Qt1DV8syI8C9jjYfFsrUs2SZir3Gx4q1oOHPEzWMBq1acGLTnxpelfm59WjJf2k/9MsZ9OLHj3bwd8648+/HwwS+BT+x8HPbw4s2/RoWuVzhuys0fU/e9Pbv3mN9FFv+ODrasde6vq6+9i71078DdAZ81LrS9eMjY5yrvC19/3fgnCbffcnnJhhZm6nGGX3cbaTfUR54tmF5tErq23Gru1QYXhPy952BuVBUo4oOTaUfcTeN1iBSAqVVVYn+mYRhhfSoSaNR6A7L0W44agpihTzTKh1+EJGrGmYebnWVgkcSdiJhV56XWmHpSmugkgjUmyVp4LVHHIpekLcbjd1+CaaaZZaJ55pRrtukml/YFmOabdNZp55140skRej4+N2dWHDaplFFVRlfoTuON2aOHwaVI4J8f9nlflAE6mVycdPVJKaITZgdcRyuq+OKhut236EqKXjojU7L5GaN3/4n/6Fx1D4GKFKObnpgca7kSOZqgtF5J4asydqqhrWHNFmeDmdYa64bWEbapgMpKW+2WQdLnX5ahBboYkkoa6SuzxQKKrLGn/Ujfousd2qqVlxL2LbGZKbctupLeyN+osMkKWqqkrjjko/LCB+y43uZ7L7Y0fmUbvcjV53Cw2f6446MQM/oSxULdeK27/ibYa6kKh8txvSQeLHBs5GIp5paimXwVgPlBKueIbb2L8oLlkevWjt0iiNmvO4eq65XxYRpmggxLvGeN8D6MpoK7Egmvunba5aibMm0dntcpFTZyawDryN6Z9trsFZV5tu220W/HLffcdNdt9905Kz1S2Xj3/+3334D/vSzfHuupdsX/Et7v2LoZyfikzwae7OG0Pf4vxk7/vJflhed7HeVNoqg335YrTnKIiZq+qsbcubz3mE+z7rHeYY87O+3zUkwt6J6rPiynSnI7nanOckq2gXnjy2qFsDKPdVYZ174a2C+fGiTncqJrnmAH6py4vsEHHzbPHO+3W/cDV6518p6jHr36zgds8MnCEgpyjrnC9C7n1n4mNa9Ji5zs3rc20W0ldsQD4ADX5izncc9agFLZzhLGOqp1LFsuUpd/HuieJGWQYWL70garlSZxEbB6DrLV/nzXrPdRj17rY6CNumazqdhwhC+EmsDA5TpEPQl7gVndBf+l1JkDBq199aqSB8t1JCTucIFDvBDi1lU8JUqHiT5rVNM2pKpy6RCKBSwS/kZXnBxCr4FgPN4P2Vc+rR0xhUKMYuIc18Y3YhFzXpRfWoqVNv+ZMGAuGlD/cufFyXQLhXLUoyLD2CIG2XGRhhwUGvM4RwrGUZGDJCTINNmX/wjRk5IKZB0/uUYJZuhs4jnZBzkpI1DiypLD653DDOjHLC7ylq8JH3sEmEgepqqPPTwO0NjIx1X2rGJLQt8jRXnKZEbrh27EXRorM0G2aU5osRLdFsmjvAh604nXBGLnOsg7fb2unNNBp+xYaBJxGu9oqEKgTbqYrG0K03vm7FQM84Q/PHZ26Y+Ga103yaTOdpaxoASr4j+Zg7YmKtR2A+VaLRG6UHeijqJJnObn3oRKuvnTapILaSxFStKSmvSkIwkIADs="/>.</li></ol></ol>
```

**Comment by Moonbase59** [comment] 2022-02-01 22:09
Ok, did a:

```bash
pip3 uninstall pyglossary
git clone https://github.com/ilius/pyglossary.git
cd pyglossary
python3 setup.py install --user
```

Ran command above:
```bash
python3 -m wikidict fr --gen-dict='cercle unité' --output=test_wik --format=stardict
```

Output:
```text
matthias@e6510:~/Projekte/ebook-reader-dict$ python3 -m wikidict fr --gen-dict='cercle unité' --output=test_wik --format=stardict
>>> Generated dict-fr-fr.df (4,595 bytes)
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/matthias/Projekte/ebook-reader-dict/wikidict/__main__.py", line 122, in <module>
    sys.exit(main())
  File "/home/matthias/Projekte/ebook-reader-dict/wikidict/__main__.py", line 101, in main
    return gen_dict.main(
  File "/home/matthias/Projekte/ebook-reader-dict/wikidict/gen_dict.py", line 25, in main
    run_formatter(StarDictFormat, *args)
  File "/home/matthias/Projekte/ebook-reader-dict/wikidict/convert.py", line 399, in run_formatter
    formater.process()
  File "/home/matthias/Projekte/ebook-reader-dict/wikidict/convert.py", line 356, in process
    self._convert()
  File "/home/matthias/Projekte/ebook-reader-dict/wikidict/convert.py", line 327, in _convert
    Glossary.init()
  File "/home/matthias/.local/lib/python3.8/site-packages/pyglossary/glossary.py", line 1153, in init
    cls.loadPluginsFromJson(pluginsJsonPath)
  File "/home/matthias/.local/lib/python3.8/site-packages/pyglossary/plugin_manager.py", line 53, in loadPluginsFromJson
    with open(jsonPath) as _file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/matthias/.local/lib/python3.8/site-packages/plugins-meta/index.json'
Traceback locals:
    cls = <class 'pyglossary.glossary.Glossary'>
    jsonPath = '/home/matthias/.local/lib/python3.8/site-packages/plugins-met...
    len(jsonPath) = 73
    json = <module 'json' from '/usr/lib/python3.8/json/__init__.py'>
    dirname = <function dirname at 0x7f479ae67820>
    join = <function join at 0x7f479ae67550>
```

**Comment by ilius** [comment] 2022-02-02 03:58
Please pull and try again.

**Comment by ilius** [comment] 2022-02-02 06:11
Please use `pip install . -U` instead

**Comment by BoboTiG** [comment] 2022-02-02 11:50
That's better :+1: 

```shell
error in DataEntry.save: [Errno 2] No such file or directory: '/home/tiger-222/.cache/pyglossary/dict-de-de.df_res/39280735.gif'
error in DataEntry.save: [Errno 2] No such file or directory: '/home/tiger-222/.cache/pyglossary/dict-de-de.df_res/39280735.gif'
error in DataEntry.save: [Errno 2] No such file or directory: '/home/tiger-222/.cache/pyglossary/dict-de-de.df_res/490fdc4a.gif'
error in DataEntry.save: [Errno 2] No such file or directory: '/home/tiger-222/.cache/pyglossary/dict-de-de.df_res/76993ec3.gif'
error in DataEntry.save: [Errno 2] No such file or directory: '/home/tiger-222/.cache/pyglossary/dict-de-de.df_res/76993ec3.gif'
error in DataEntry.save: [Errno 2] No such file or directory: '/home/tiger-222/.cache/pyglossary/dict-de-de.df_res/ba1f03ff.gif'
error in DataEntry.save: [Errno 2] No such file or directory: '/home/tiger-222/.cache/pyglossary/dict-de-de.df_res/f6d31a88.gif'
>>> Generated dict-de-de.zip (10,590,910 bytes)
```

**Comment by BoboTiG** [comment] 2022-02-02 11:51
And ever better :muscle: 

```shell
$ python -m wikidict fr --gen-dict='cercle unité' --output=test_wik --format=stardict
>>> Generated dict-fr-fr.df (4,595 bytes)
No module named 'pyglossary.plugin_lib.py310'
>>> Generated dict-fr-fr.zip (4,246 bytes)
```

**Comment by BoboTiG** [comment] 2022-02-02 11:53
> error in DataEntry.save: [Errno 2] No such file or directory: '/home/tiger-222/.cache/pyglossary/dict-de-de.df_res/39280735.gif'

BTW @ilius is it expected that the GIF is not found?

**Comment by ilius** [comment] 2022-02-02 13:49
> BTW @ilius is it expected that the GIF is not found?

https://github.com/ilius/pyglossary/commit/11b2c3a2ede3a8efde6ce2d7ccc1a424b1ba3bec
Please try again.
Should not see that error again.

**Comment by ilius** [comment] 2022-02-02 13:52
Is there a way to set the number of workers in `--render`?

**Comment by BoboTiG** [comment] 2022-02-02 13:58
> > BTW @ilius is it expected that the GIF is not found?
> 
> [ilius/pyglossary@11b2c3a](https://github.com/ilius/pyglossary/commit/11b2c3a2ede3a8efde6ce2d7ccc1a424b1ba3bec) Please try again. Should not see that error again.

Works perfectly, thanks!

**Comment by BoboTiG** [comment] 2022-02-02 13:59
> Is there a way to set the number of workers in `--render`?

Not yet. I'm on it!

**Comment by BoboTiG** [comment] 2022-02-02 14:36
> Is there a way to set the number of workers in `--render`?

@ilius , you are good to go: `--render --workers=N` :heavy_check_mark:

**Comment by Moonbase59** [comment] 2022-02-02 15:06
Did a quick one using fresh pulls: Fast, no errors on:

```bash
cercle unité' --output=test_wik --format=stardict
>>> Generated dict-fr-fr.df (4,595 bytes)
>>> Generated dict-fr-fr.zip (4,246 bytes)
```
Using [ilius’ GoldenDict theme](https://gist.github.com/ilius/5a2f35c79775267fbdb249493c041453/), we can see why raster images are bad, especially w/o transparancy:

![cercle unité - GoldenDict_001](https://user-images.githubusercontent.com/3706922/152180072-06d22788-3210-4110-9f68-77b21bec56fe.png)

Will be trying the `--workers` now. Yesterday got a load of 14 (!) on a quad-core laptop (8 threads).

**Comment by ilius** [comment] 2022-02-02 15:09
> @ilius , you are good to go: --render --workers=N ✔️

Thanks.
I'm still not sure how `multiprocessing.Pool()` works.
For example when I pass `--workers=2`, it results in `Pool(processes=2)` correctly.
But I can see 10 processes (PIDs) (9 children), only 2 of them running at the same time (the rest are sleep).

**Comment by Moonbase59** [comment] 2022-02-02 15:10
Using workers=4 here, it jumps between 2 and 4 active.

**Comment by Moonbase59** [comment] 2022-02-02 19:06
Possible that there’s something wrong with that still?

I could previously (no workers) generate a complete dict, although it would use almost all resources on my laptop. Using `workers=4` now, it produces full RAM (122 MB left of 8 GB, 0 bytes left on swap), and swaps itself to death (load average above 40!), had to pull the plug.

**Comment by Moonbase59** [comment] 2022-02-02 19:09
I see workers+1 python3 processes in `top`, each reserving 2.4 GB RAM. Trying workers=2 now.

**Comment by ilius** [comment] 2022-02-02 23:13
Can we close this issue?

**Comment by Moonbase59** [comment] 2022-02-03 01:50
Ok with me.

**Closed** 2022-02-03 08:35 UTC
